### PR TITLE
replace `system-fileio` with `directory`

### PR DESCRIPTION
**Pull request by peterbecich**
test suite passes

closes: https://github.com/haskell-hvr/http-io-streams/issues/17

### CODE REVIEW

**Comment by peterbecich** [comment]
@andreasabel can this merged? Can a fix version be published? Thanks

**Comment by andreasabel** [comment]
Candidate: https://hackage.haskell.org/package/http-io-streams-0.1.6.4/candidate

**Comment by peterbecich** [comment]
thanks

**Comment by andreasabel** [comment]
Published, thank you very much, Peter!

**Pull request merged**
